import React from "react";
import ReactDom from "react-dom";
import { LightBar } from "./components/Bulb";
import { TimeBar } from "./components/TimeBar";
import { TodoList } from "./components/todoList";
import { SearchBar } from "../src/components/SearchBar";
import HOC from "../src/components/HOC";
import { HookDemo } from "../src/components/HookUseDemo";
import App from "../src/components/temp";
import { ChangeNumReducx } from "./components/ReduxUseDemo";
import ExClusiveLi from "../src/practice/exclusive";
import Pw from "../src/practice/PasswordRevealer";
import Slider from "../src/practice/slider";
import Checkbox from "./practice/select";
import Timer from "../src/practice/timeCountDown";
//ReactDom.render(<HookDemo />, document.getElementById("root"));
//ReactDom.render(<LightBar />, document.getElementById("root"));
//ReactDom.render(<TimeBar />, document.getElementById("root"));
//ReactDom.render(<HOC title="我是高阶组件体验人员" />,document.getElementById("root"));
//ReactDom.render(<TodoList />, document.getElementById("root"));
//ReactDom.render(<SearchBar />, document.getElementById("root"));
//ReactDom.render(<App />, document.getElementById("root"));
//ReactDom.render(<ExClusiveLi />, document.getElementById("root"));
//ReactDom.render(<Pw />, document.getElementById("root"));
//ReactDom.render(<Slider />, document.getElementById("root"));
//ReactDom.render(<Checkbox />, document.getElementById("root"));
//ReactDom.render(<Timer />, document.getElementById("root"));
